### ISSUE TITLE
panic - Conflicting window flags specified

### ISSUE THREAD

**Issue by renatorabelo** [massung/CHIP-8#4]
Hi, 
I'm trying to build your emulator but i get a panic with the binary. 

panic: Conflicting window flags specified
goroutine 1 [running, locked to thread]:
main.createWindow()
        C:/Users/rsrim/go/src/github.com/massung/CHIP-8/main.go:217 +0x17d
main.main()
        C:/Users/rsrim/go/src/github.com/massung/CHIP-8/main.go:173 +0x274

Any ideas ?

**Comment by renatorabelo** [comment]
https://github.com/massung/CHIP-8/blob/master/main.go#L212 should be 
`flags := sdl.WINDOW_OPENGL`

**Comment by massung** [comment]
Pushed a version with the fix. Looks like the "centered" flag was for a different argument and the latest SDL version recognized the incorrect flag.

Thanks for finding that!

**Comment by massung** [comment]
Published a new release with the fix as well. Special thanks to you in it. ;-)
