### ISSUE TITLE
no sound - latest release - windows

### ISSUE THREAD

**Issue by renatorabelo** [massung/CHIP-8#5]
I can't get bip sounds from this release.

**Comment by renatorabelo** [comment]
Hmmm... i dont get beep sounds from any releases. My problem here.

**Comment by renatorabelo** [comment]
Do you have any idea why i cant get beep sounds ?

**Comment by massung** [comment]
Well, I supposed it boils down to either A) the timers or B) the sound generation code to SDL. 

Does the delay timer work alright? Load up `games/source/clock.c8` (I just pushed a fixed version of it) and see if that works. If that's not working, likely your version of Go and/or platform combination isn't returning a good value for `time.Now().UnixNano()`.

If it does work, then you'll need to test the `Tone` function in main.go and whether or not. Best way I can think to do that is to hack up the `ST` register.

https://github.com/massung/CHIP-8/blob/master/main.go#L183

By that point `VM` has been initialized and a program is running. You could bash `VM.ST` at that point to something quite large and just make the program emit a solid tone for a long time.

Let me know what happens!

**Comment by renatorabelo** [comment]
I have sound now. Strange. Already closed this issue.
