### ISSUE TITLE
[NOT Bug][Question] How was font.bmp made?

### ISSUE THREAD

**Issue by kaishuu0123** [massung/CHIP-8#9]
Hello, @massung.

<img src="https://raw.githubusercontent.com/massung/CHIP-8/master/font.bmp" />

* https://raw.githubusercontent.com/massung/CHIP-8/master/font.bmp

Above is your 5x7 font file, what **tools** and **fonts** did you use to generate it?

I feel it is a very beautiful bitmap font. I'm glad if you can answer.

**Comment by massung** [comment]
I used https://www.aseprite.org/ - absolutely love it. The font was hand-made by me, though. I have two other versions of the same font (4-pixel wide characters and another that is 8). If either would be useful for you on any of your projects, just email me and I'll send them your way.

**Comment by kaishuu0123** [comment]
@massung Thanks for the great answer!
Handmade is amazing! I think it's a cool font. If I use your fonts, I will definitely contact you.
